language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
  - "pypy3"
addons:
  apt:
    packages:
      - graphviz
matrix:
  include:
    - os: osx
      osx_image: xcode12
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.8
      before_install: brew install graphviz
  allow_failures:
    - os: osx
    - python: "3.9-dev"
    - python: "pypy3"

before_install:
  # create new empty venv
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      - git clone https://github.com/matthew-brett/multibuild;
      - source multibuild/osx_utils.sh;
      - get_macpython_environment $TRAVIS_PYTHON_VERSION venv;
    else
      - virtualenv -p python ~/venv;
      - source ~/venv/bin/activate;
    fi
install:
  # install required packages
  - pip install --upgrade pip
  - pip install -r requirements/test.txt
  # install pygraphviz
  - printenv PWD
  - pip install -e .
  # show what's installed
  - python --version
  - pip list
script:
  - nosetests --with-coverage --cover-package=pygraphviz
  - python setup.py bdist_wheel
after_success:
  - coveralls
