language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6-dev"
  - "pypy"
before_install:
  # We need GraphViz
  - "sudo apt-get install graphviz 2>&1 | tail -n 2"
install:
  - pip install mock
  - pip install nose
  - pip install doctest-ignore-unicode
  - pip install coveralls
  - python setup.py develop
script:
  - nosetests --with-coverage --cover-package=pygraphviz
after_success:
  - coveralls
